default:
  image: nixos/nix:latest

stages:
   - check
   - build
   - test

variables:
  NIX_CONFIG: "experimental-features = nix-command flakes"

format:
  stage: check
  when: always
  script: |
    echo "Formatting the application..."
    nix develop --command pre-commit run --all-files

build:
  stage: build
  when: always
  script: |
      echo "Building gbox..."
      nix build .# --system x86_64-linux --no-link --print-build-logs

build-examples:
  stage: build
  when: always
  script: |
    echo "Building gbox-mono example for desktop..."
    cd examples/gbox-mono && nix build .#

    cd ../..

unit:
  stage: test
  script: |
    echo "Building gbox-mono repository unit tests..."

    // TODO: ACTUALLY DO UNIT TESTS IN CI
