default_install_hook_types: [pre-commit, pre-push]

repos:
- repo: local
  hooks:
    - id: clang-format
      name: clang-format
      entry: clang-format -i
      language: system
      files: '\.(cpp|hpp|cppm|c|h|cc|hh|cxx|hxx|proto|cs|cu)$'
      exclude: ^examples/stm32f446/gen/
    - id: clang-tidy
      name: clang-tidy
      entry: run-clang-tidy -p build -quiet -source-filter '(?!.*/test/).*'
      language: system
      stages: [pre-push]
      pass_filenames: false
      files: '\.(cpp|cppm|c|cc|cxx|cu)$'
      exclude: ^examples/stm32f446/gen/
