repos:
- repo: local
  hooks:
    - id: clang-format
      name: clang-format
      entry: clang-format -i
      language: system
      files: '\.(cpp|hpp|cppm|c|h|cc|hh|cxx|hxx|proto|cs|cu)$'
      exclude: ^examples/stm32f446/gen/
    - id: clang-tidy
      name: clang-tidy
      entry: clang-tidy -p build --quiet
      language: system
      files: '\.(cpp|cppm|c|cc|cxx|cu)$'
      exclude: ^examples/stm32f446/gen/
