# AddModule.cmake
#
# This file implements a method of marking a directory as a module.
#
# A module is any set of src, inc, and test code that makes up a "member" of the overall project.
# `gbox_module()` runs one module end to end: it names the module, hands the directory to
# `add_subdirectory()` so the module can declare itself, picks up its tests, and finally installs
# and exports what the directory built.
#
# Installation lives here rather than in the root CMakeLists.txt so that adding a module to the
# workspace is a single call with no second place to register it.

include(GNUInstallDirs)
include(CMakePackageConfigHelpers)

# Where the package lands. `share/cmake/gbox` is a location find_package() searches, so a consumer
# needs only the install prefix on CMAKE_PREFIX_PATH.
set(GBOX_INSTALL_CMAKE_DIR "${CMAKE_INSTALL_DATADIR}/cmake/gbox")
set(GBOX_INSTALL_MODULE_DIR "${CMAKE_INSTALL_LIBDIR}/gbox/modules")

# This file ships to consumers as part of the package, where `gbox_module()` is theirs to call
# against their own sources. Exporting is meaningful only while building gbox itself.
if(PROJECT_IS_TOP_LEVEL AND PROJECT_NAME STREQUAL "gbox")
    set(GBOX_WORKSPACE TRUE)
else()
    set(GBOX_WORKSPACE FALSE)
endif()

# The registry naming every component the package offers. Each module appends itself as it is
# configured, and a reconfigure starts from an empty file so entries cannot accumulate.
set(GBOX_COMPONENT_REGISTRY "${PROJECT_BINARY_DIR}/gboxComponents.cmake")

# Where this file's siblings live, so that locating them does not depend on a variable the
# including project happens to have set.
set(GBOX_CMAKE_DIR "${CMAKE_CURRENT_LIST_DIR}")

if(GBOX_WORKSPACE)
    file(
      WRITE "${GBOX_COMPONENT_REGISTRY}"
      "# Generated by gbox_module(). Lists the components this build of gbox offers.\n"
    )

    # The package config reads the registry when a consumer calls find_package(), not now, so it
    # can be written before a single module has registered itself.
    configure_package_config_file(
      "${GBOX_CMAKE_DIR}/gboxConfig.cmake.in"
      "${PROJECT_BINARY_DIR}/gboxConfig.cmake"
      INSTALL_DESTINATION "${GBOX_INSTALL_CMAKE_DIR}"
    )

    write_basic_package_version_file(
      "${PROJECT_BINARY_DIR}/gboxConfigVersion.cmake"
      COMPATIBILITY SameMajorVersion
    )

    install(
      FILES
        "${PROJECT_BINARY_DIR}/gboxConfig.cmake"
        "${PROJECT_BINARY_DIR}/gboxConfigVersion.cmake"
        "${GBOX_COMPONENT_REGISTRY}"
        "${GBOX_CMAKE_DIR}/AddModule.cmake"
        "${GBOX_CMAKE_DIR}/AddLibrary.cmake"
        "${GBOX_CMAKE_DIR}/AddTests.cmake"
      DESTINATION "${GBOX_INSTALL_CMAKE_DIR}"
    )
endif()

# Installs a library and the export set it is reachable through downstream.
#
# Which file sets a library carries varies by module -- one may publish headers, another only
# module interface units -- and naming a file set the target never declared is an error, so the
# argument list is built from what the target actually has.
function(gbox_install_library TARGET COMPONENT)
    set(EXPORT_SET "gbox${COMPONENT}Targets")
    set(INSTALL_ARGS ARCHIVE DESTINATION "${CMAKE_INSTALL_LIBDIR}")

    get_target_property(HEADER_SETS "${TARGET}" INTERFACE_HEADER_SETS)
    if(HEADER_SETS)
        list(
          APPEND INSTALL_ARGS
          FILE_SET HEADERS DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}"
        )
    endif()

    get_target_property(MODULE_SETS "${TARGET}" INTERFACE_CXX_MODULE_SETS)
    if(MODULE_SETS)
        # Ship the interface units and let a consumer compile its own BMIs from them. A clang BMI
        # is only valid for the flags it was produced with, so shipping ours would bind every
        # consumer to this build's exact configuration.
        list(
          APPEND INSTALL_ARGS
          FILE_SET CXX_MODULES DESTINATION "${GBOX_INSTALL_MODULE_DIR}/${COMPONENT}"
          CXX_MODULES_BMI DESTINATION ""
        )
    endif()

    install(TARGETS "${TARGET}" EXPORT "${EXPORT_SET}" ${INSTALL_ARGS})

    # CXX_MODULES_DIRECTORY is what carries the module information across the package boundary.
    # Without it the interface units install but no consumer can import them.
    install(
      EXPORT "${EXPORT_SET}"
      FILE "${EXPORT_SET}.cmake"
      NAMESPACE gbox::
      CXX_MODULES_DIRECTORY cxx-modules
      DESTINATION "${GBOX_INSTALL_CMAKE_DIR}"
    )
endfunction()

# Installs a binary as a program. Binaries join no export set, since nothing links them.
function(gbox_install_binary TARGET)
    # Test builds drop the apps from the `all` target, and installing a target that was never
    # built fails at install time.
    if(GBOX_BUILD_TEST)
        return()
    endif()

    install(TARGETS "${TARGET}" RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}")
endfunction()

# Adds a component's imported dependencies to its export set.
#
# An import is a real INTERFACE target carrying the third-party link entries, and a library that
# links one names it in its own interface. CMake will not export a target whose interface reaches
# a target belonging to no export set, so the imports travel with the component that uses them.
function(gbox_export_imports COMPONENT)
    foreach(DEPENDENCY IN LISTS ARGN)
        if(TARGET "import::${DEPENDENCY}")
            install(TARGETS "import_${DEPENDENCY}" EXPORT "gbox${COMPONENT}Targets")
        endif()
    endforeach()
endfunction()

# Writes the file a consumer includes to obtain one component, and adds that component to the
# package registry.
#
# A component is responsible for everything its targets need: the packages an imported dependency
# resolves to, and the other components an in-tree dependency lives in. Naming a component in
# find_package() therefore brings its prerequisites with it, and naming none of them costs a
# consumer nothing.
function(gbox_register_component COMPONENT)
    set(COMPONENT_FILE "${PROJECT_BINARY_DIR}/gbox${COMPONENT}Component.cmake")

    # `core` is a prerequisite of several components, and including its export set twice would
    # redefine the imported targets. GLOBAL rather than the default directory scope, since a
    # consumer may find_package() from more than one directory.
    set(CONTENT "include_guard(GLOBAL)\n\ninclude(CMakeFindDependencyMacro)\n\n")

    foreach(DEPENDENCY IN LISTS ARGN)
        if(TARGET "import::${DEPENDENCY}")
            get_property(PACKAGE GLOBAL PROPERTY "GBOX_IMPORT_${DEPENDENCY}_PACKAGE")
            get_property(COMPONENTS GLOBAL PROPERTY "GBOX_IMPORT_${DEPENDENCY}_COMPONENTS")

            # An import declared without a package contributes include directories only; there is
            # nothing for a consumer to go find.
            if(PACKAGE)
                if(COMPONENTS)
                    string(REPLACE ";" " " COMPONENTS "${COMPONENTS}")
                    string(APPEND CONTENT "find_dependency(${PACKAGE} COMPONENTS ${COMPONENTS})\n")
                else()
                    string(APPEND CONTENT "find_dependency(${PACKAGE})\n")
                endif()
            endif()
        else()
            string(
              APPEND CONTENT
              "include(\"\${CMAKE_CURRENT_LIST_DIR}/gbox${DEPENDENCY}Component.cmake\")\n"
            )
        endif()
    endforeach()

    string(
      APPEND CONTENT
      "\ninclude(\"\${CMAKE_CURRENT_LIST_DIR}/gbox${COMPONENT}Targets.cmake\")\n"
      "set(gbox_${COMPONENT}_FOUND TRUE)\n"
    )

    file(WRITE "${COMPONENT_FILE}" "${CONTENT}")
    install(FILES "${COMPONENT_FILE}" DESTINATION "${GBOX_INSTALL_CMAKE_DIR}")

    file(
      APPEND "${GBOX_COMPONENT_REGISTRY}"
      "list(APPEND gbox_SUPPORTED_COMPONENTS ${COMPONENT})\n"
    )
endfunction()

# Installs and exports whatever a module's directory declared.
#
# The directory's dependencies apply to every component it produced. A directory holding one
# library -- the shape every module in the workspace currently takes -- makes that exact.
function(gbox_export_module MODULE_PATH)
    if(NOT GBOX_WORKSPACE)
        return()
    endif()

    get_property(LIBRARIES DIRECTORY "${MODULE_PATH}" PROPERTY GBOX_DIR_LIBRARIES)
    get_property(BINARIES DIRECTORY "${MODULE_PATH}" PROPERTY GBOX_DIR_BINARIES)
    get_property(DEPENDENCIES DIRECTORY "${MODULE_PATH}" PROPERTY GBOX_DIR_DEPENDENCIES)

    foreach(TARGET IN LISTS LIBRARIES)
        get_target_property(COMPONENT "${TARGET}" GBOX_COMPONENT)

        gbox_install_library("${TARGET}" "${COMPONENT}")
        gbox_export_imports("${COMPONENT}" ${DEPENDENCIES})
        gbox_register_component("${COMPONENT}" ${DEPENDENCIES})
    endforeach()

    foreach(TARGET IN LISTS BINARIES)
        gbox_install_binary("${TARGET}")
    endforeach()
endfunction()

# Marks a directory as a gbox module and runs it end to end.
#
#   gbox_module(GBOX_CORE "${PROJECT_SOURCE_DIR}/libs/core")
#
# MODULE_NAME is the prefix the module's discovered paths and sources are published under, so
# that the directory's own CMakeLists.txt finds them in scope:
#
#   <MODULE_NAME>_PATH         the module's root
#   <MODULE_NAME>_SRC_PATH     src/, and _INC_PATH, _TEST_PATH alongside it
#   <MODULE_NAME>_SRC          globbed .c and .cpp sources, less any entry point
#   <MODULE_NAME>_MODULE_SRC   globbed .cppm interface units, less any entry point
#
# The module then declares itself with gbox_library() or gbox_binary(), its tests are picked up
# if it has any, and what it built is installed and exported.
macro(gbox_module MODULE_NAME MODULE_PATH)
  set("${MODULE_NAME}_PATH" "${MODULE_PATH}")
  string(TOLOWER "${MODULE_NAME}" "${MODULE_NAME}_LIB_NAME")

  set("${MODULE_NAME}_NAME" "${${MODULE_NAME}_LIB_NAME}")
  set("${MODULE_NAME}_SRC_PATH" "${MODULE_PATH}/src")
  set("${MODULE_NAME}_INC_PATH" "${MODULE_PATH}/inc")
  set("${MODULE_NAME}_TEST_PATH" "${MODULE_PATH}/test")

  file(
    GLOB_RECURSE
    "${MODULE_NAME}_SRC"
    "${${MODULE_NAME}_SRC_PATH}/*.c" "${${MODULE_NAME}_SRC_PATH}/*.cpp"
  )

  file(
    GLOB_RECURSE
    "${MODULE_NAME}_MODULE_SRC"
    "${${MODULE_NAME}_SRC_PATH}/*.cppm"
  )

  list(REMOVE_ITEM "${MODULE_NAME}_SRC" "${${MODULE_NAME}_SRC_PATH}/main.cpp")
  list(REMOVE_ITEM "${MODULE_NAME}_SRC" "${${MODULE_NAME}_SRC_PATH}/main.c")
  list(REMOVE_ITEM "${MODULE_NAME}_MODULE_SRC" "${${MODULE_NAME}_SRC_PATH}/main.cppm")

  # Which module the subdirectory belongs to, so that gbox_library() and gbox_binary() can reach
  # the variables above without deriving the prefix from their own argument.
  set(GBOX_CURRENT_MODULE "${MODULE_NAME}")

  add_subdirectory("${${MODULE_NAME}_PATH}")
  if(EXISTS "${${MODULE_NAME}_TEST_PATH}/CMakeLists.txt")
    add_subdirectory("${${MODULE_NAME}_TEST_PATH}")
  else()
    message(
      STATUS
      "gbox module ${MODULE_NAME}: no test directory at ${${MODULE_NAME}_TEST_PATH}, "
      "tests skipped."
    )
  endif()

  gbox_export_module("${${MODULE_NAME}_PATH}")
endmacro()
